FROM openjdk:8-jdk-alpine
ARG JAR_FILE=target/*.jar
copy ./target/order-service-0.0.1-SNAPSHOT.jar order-service-0.0.1-SNAPSHOT.jar
CMD ["java","-jar","order-service-0.0.1-SNAPSHOT.jar"]
RUN chmod 777 order-service-0.0.1-SNAPSHOT.jarENTRYPOINT ["java", "-jar", "/app.jar"]
ENTRYPOINT ["java", "-jar", "/app.jar"]
